spring:
  datasource:
    url: jdbc:mysql://60.204.224.204:3306/vine?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    username: root
    password: Nw6zOd=hfbhz.
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: always
    continue-on-error: true
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 3000
      pool-name: SpringBootDemoHikariCP
      max-lifetime: 6000
      connection-timeout: 3000

logging:
  level:
    com.sflc.ad: debug
    com.sflc.ad.mapper: trace

mybatis-plus:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.starlight.model

server:
  servlet:
    context-path: /starlight

log:
  path: /opt/starlight/logs


starlight:
  domain: http://60.204.224.204/starlight
  invite:
    uri: /link